### ISSUE TITLE
Todo Refacto 

### ISSUE THREAD

**Issue by the-smaug** [the-smaug/site-blend-program-generator#80]
- [ ] convention de nommage pour le blender
- [ ] ajouter flow sur l'ensemble de l'application
- [ ] destructuring dans les reducers ?
